/**
 * go2rtc Sidecar Process Manager
 *
 * Runs a bundled go2rtc binary as a child process to repackage UDP-RTP and
 * RTSP H.264 sources into WebRTC/WHEP streams the renderer can consume in a
 * plain <video> element. Pattern mirrors ardupilot-sitl-process.ts.
 *
 * go2rtc HTTP/WHEP API listens on 127.0.0.1:1984 by default. Renderer hits:
 *   GET  http://127.0.0.1:1984/api/streams                 → list
 *   POST http://127.0.0.1:1984/api/webrtc?src=<id>         → SDP offer/answer (WHEP)
 */

import { spawn, ChildProcess } from 'node:child_process';
import { app, BrowserWindow } from 'electron';
import { chmod, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { VideoSource, VideoSidecarStatus } from '../../shared/ipc-channels.js';
import { IPC_CHANNELS } from '../../shared/ipc-channels.js';

export const GO2RTC_API_PORT = 1984;

function resolveBinaryPath(): string {
  // electron-builder asarUnpack puts resources under app.asar.unpacked in
  // production. In dev (electron-vite) we run from repo root with the source
  // tree intact, so resources/ sits next to package.json.
  const binName = process.platform === 'win32' ? 'go2rtc.exe' : 'go2rtc';
  if (app.isPackaged) {
    return path.join(app.getAppPath() + '.unpacked', 'resources', 'go2rtc', binName);
  }
  // Dev: walk up from apps/desktop/ to repo root.
  return path.join(app.getAppPath(), 'resources', 'go2rtc', binName);
}

/** Per-source SDP file describing the raw H.264 RTP stream so ffmpeg can demux it. */
function sdpForUdpRtp(port: number): string {
  return [
    'v=0',
    'o=- 0 0 IN IP4 127.0.0.1',
    's=ArduDeck',
    'c=IN IP4 127.0.0.1',
    't=0 0',
    `m=video ${port} RTP/AVP 96`,
    'a=rtpmap:96 H264/90000',
    'a=fmtp:96 packetization-mode=1',
    '',
  ].join('\n');
}

/**
 * Build a go2rtc YAML config from the active source list.
 *
 * Source URL conventions:
 *   - rtsp: pass the URL through verbatim (go2rtc handles RTSP natively)
 *   - udp-rtp: go2rtc has no built-in raw-RTP source, and its `ffmpeg:` URL
 *     scheme doesn't auto-inject `-i` for SDP inputs (verified empirically —
 *     ffmpeg gets spawned with all our flags but no input file path). The
 *     working pattern is `exec:` with a full ffmpeg command including the
 *     `{output}` token go2rtc substitutes with its internal RTSP target.
 *     `-analyzeduration` / `-probesize` must be generous so ffmpeg waits for
 *     a keyframe + SPS/PPS before giving up on auto-detection.
 */
function buildConfigYaml(sources: VideoSource[], sdpDir: string): string {
  const lines: string[] = [];
  lines.push('# Generated by ArduDeck — do not edit by hand.');
  lines.push('api:');
  lines.push(`  listen: 127.0.0.1:${GO2RTC_API_PORT}`);
  // CORS — in dev the renderer is served from the Vite dev server origin
  // (http://localhost:517x) and fetches go2rtc on a different origin, so
  // the browser blocks WHEP without Access-Control-Allow-Origin. In prod
  // the renderer loads from file:// which is also a separate origin. Bind
  // to localhost only (above), so wildcard origin is safe.
  lines.push('  origin: "*"');
  lines.push('webrtc:');
  lines.push('  candidates:');
  lines.push('    - 127.0.0.1:8555');
  lines.push('log:');
  lines.push('  level: warn');
  lines.push('streams:');
  if (sources.length === 0) {
    lines.push('  # (no sources configured)');
    return lines.join('\n') + '\n';
  }
  for (const src of sources) {
    let url: string;
    if (src.type === 'rtsp') {
      url = src.url ?? '';
    } else {
      const port = src.port ?? 5600;
      const sdpPath = path.join(sdpDir, `${src.id}.sdp`);
      // The SDP path almost always contains spaces on macOS
      // (`~/Library/Application Support/...`). go2rtc's exec parser splits
      // unquoted whitespace into separate args, so the path must be
      // double-quoted or ffmpeg sees "-i /Users/.../Library/Application"
      // followed by garbage and silently produces no input.
      url =
        `exec:ffmpeg -hide_banner -loglevel error ` +
        `-protocol_whitelist file,udp,rtp ` +
        `-analyzeduration 5000000 -probesize 5000000 ` +
        `-fflags +nobuffer -flags low_delay ` +
        `-i "${sdpPath}" ` +
        `-c:v copy -an ` +
        `-f rtsp -rtsp_transport tcp {output}`;
      // Mark for sidecar to know we need to write this SDP file.
      lines.push(`  # ${src.id}: udp-rtp listener on port ${port}, SDP at ${sdpPath}`);
    }
    // Wrap in single quotes so the inline `"..."` around the SDP path
    // (needed because the userData path on macOS contains spaces) doesn't
    // collide with the YAML string delimiter. Single-quoted YAML escapes
    // a literal single quote by doubling it.
    const yamlEscaped = url.replace(/'/g, "''");
    lines.push(`  ${src.id}: '${yamlEscaped}'`);
  }
  return lines.join('\n') + '\n';
}

class Go2rtcProcessManager {
  private process: ChildProcess | null = null;
  private _isRunning = false;
  private mainWindow: BrowserWindow | null = null;
  private _activeSources: VideoSource[] = [];
  private _configPath: string | null = null;

  get isRunning(): boolean {
    return this._isRunning;
  }

  get activeSources(): VideoSource[] {
    return this._activeSources;
  }

  setMainWindow(window: BrowserWindow): void {
    this.mainWindow = window;
  }

  private getConfigPath(): string {
    return path.join(app.getPath('userData'), 'video', 'go2rtc.yaml');
  }

  /**
   * Start (or restart) go2rtc with the given source list. Always tears down
   * any running instance first so source-list edits take effect immediately.
   */
  async start(sources: VideoSource[]): Promise<{ success: boolean; error?: string }> {
    if (this._isRunning) {
      await this.stopAndWait(3000);
    }

    try {
      const binaryPath = resolveBinaryPath();
      const { access } = await import('node:fs/promises');
      try {
        await access(binaryPath);
      } catch {
        return { success: false, error: `go2rtc binary not found at ${binaryPath}` };
      }

      if (process.platform !== 'win32') {
        try { await chmod(binaryPath, 0o755); } catch { /* best effort */ }
      }

      const configPath = this.getConfigPath();
      const videoDir = path.dirname(configPath);
      await mkdir(videoDir, { recursive: true });

      // Write a per-source SDP file for every udp-rtp source. ffmpeg needs
      // this to know the codec/payload of incoming raw RTP packets — go2rtc
      // doesn't generate it for us.
      for (const src of sources) {
        if (src.type === 'udp-rtp') {
          const sdpPath = path.join(videoDir, `${src.id}.sdp`);
          await writeFile(sdpPath, sdpForUdpRtp(src.port ?? 5600), 'utf-8');
        }
      }

      await writeFile(configPath, buildConfigYaml(sources, videoDir), 'utf-8');
      this._configPath = configPath;
      this._activeSources = sources;

      this.process = spawn(binaryPath, ['-config', configPath], {
        cwd: path.dirname(binaryPath),
        stdio: ['pipe', 'pipe', 'pipe'],
      });
      this._isRunning = true;

      this.process.stdout?.on('data', (data: Buffer) => {
        this.sendToRenderer(IPC_CHANNELS.VIDEO_STDOUT, data.toString());
      });
      this.process.stderr?.on('data', (data: Buffer) => {
        this.sendToRenderer(IPC_CHANNELS.VIDEO_STDERR, data.toString());
      });
      this.process.on('error', (err: Error) => {
        console.error('[go2rtc] process error:', err);
        this._isRunning = false;
        this.sendToRenderer(IPC_CHANNELS.VIDEO_ERROR, err.message);
      });
      this.process.on('exit', (code: number | null, signal: string | null) => {
        this._isRunning = false;
        this.process = null;
        this.sendToRenderer(IPC_CHANNELS.VIDEO_EXIT, { code, signal });
      });

      return { success: true };
    } catch (err) {
      console.error('[go2rtc] failed to start:', err);
      this._isRunning = false;
      return { success: false, error: err instanceof Error ? err.message : 'Unknown error' };
    }
  }

  stop(): void {
    if (!this.process) return;
    try { this.process.kill('SIGTERM'); } catch { /* already dead */ }
    setTimeout(() => {
      if (this.process) {
        try { this.process.kill('SIGKILL'); } catch { /* already dead */ }
      }
    }, 2000);
    this.process = null;
    this._isRunning = false;
  }

  async stopAndWait(timeoutMs = 3000): Promise<void> {
    const proc = this.process;
    if (!proc) return;
    return new Promise<void>((resolve) => {
      let settled = false;
      const settle = () => { if (!settled) { settled = true; resolve(); } };
      proc.once('exit', settle);
      try {
        proc.kill('SIGTERM');
        setTimeout(() => { try { proc.kill('SIGKILL'); } catch { /* already dead */ } }, 1500);
      } catch { /* ignore */ }
      this.process = null;
      this._isRunning = false;
      setTimeout(settle, timeoutMs);
    });
  }

  getStatus(): VideoSidecarStatus {
    return {
      isRunning: this._isRunning,
      pid: this.process?.pid,
      apiPort: GO2RTC_API_PORT,
      sources: this._activeSources,
      configPath: this._configPath ?? undefined,
    };
  }

  private sendToRenderer(channel: string, data: unknown): void {
    if (this.mainWindow && !this.mainWindow.isDestroyed()) {
      this.mainWindow.webContents.send(channel, data);
    }
  }
}

export const go2rtcProcess = new Go2rtcProcessManager();
